name: namer_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1
  
dependencies:
  flutter:
    sdk: flutter
  # audioplayers: ^0.20.1
  audioplayers: ^6.0.0

  primer_progress_bar: ^0.4.1

  english_words: ^4.0.0
  provider: ^6.0.0
  

dev_dependencies: 
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # flutter_launcher_icons: ^0.13.1

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/icon/icon.png"



flutter:
  uses-material-design: true
  assets:
    - assets/images/back/
    - assets/images/character/
    - assets/images/icon/
    - assets/audios/character/
    - assets/audios/face/
